#!/usr/bin/env python3

from argparse import ArgumentParser
from pathlib import Path
from re import compile


argp = ArgumentParser(
    prog="make_tm_moves_table.py",
    description="Generate the code-table assigning TM and HM items to moves",
)
_ = argp.add_argument(
    "--schema",
    "-s",
    required=True,
    help="Path to the schema file defining the list of TMs and HMs",
)
_ = argp.add_argument(
    "--output",
    "-o",
    required=True,
    help="Path to the output header file",
)

args = argp.parse_args()
schema = Path(args.schema)
output = Path(args.output)
tmlist: list[str] = []
hmlist: list[str] = []

COMMENT = compile(r"\s*#")
HMSTART = "START: HMs"


with open(schema, "r", encoding="utf8") as inf:
    target = tmlist
    for line in inf:
        parts = list(map(lambda s: s.strip(), COMMENT.split(line)))

        if len(parts) > 1 and parts[1] == HMSTART:
            target = hmlist
            continue

        if not parts[0]:
            continue

        target.append(parts[0])

with open(output, "w") as outf_moves_h:
    print("/*", file=outf_moves_h)
    print(" * This file was generated by tools/scripts/make_tm_moves_table.py; DO NOT MODIFY IT!!!", file=outf_moves_h)
    print(" *", file=outf_moves_h)
    print(f" * Source file: {schema}", file=outf_moves_h)
    print(" */", file=outf_moves_h)
    print("", file=outf_moves_h)
    print("#ifndef POKEPLATINUM_TMHM_MOVES_H", file=outf_moves_h)
    print("#define POKEPLATINUM_TMHM_MOVES_H", file=outf_moves_h)
    print("", file=outf_moves_h)
    print('#include "constants/items.h"', file=outf_moves_h)
    print('#include "constants/moves.h"', file=outf_moves_h)
    print("", file=outf_moves_h)
    print("static const u16 sTMHMMoves[] = {", file=outf_moves_h)

    for i, move in enumerate(tmlist, start=1):
        print(f"    [TMHM_ID(TM{i:02})] = {move},", file=outf_moves_h)
    for i, move in enumerate(hmlist, start=1):
        print(f"    [TMHM_ID(HM{i:02})] = {move},", file=outf_moves_h)

    print("};", file=outf_moves_h)
    print("", file=outf_moves_h)
    print("#endif // POKEPLATINUM_TMHM_MOVES_H", file=outf_moves_h)
